/*$file${.::Core/Src/test.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: sm.qm
* File:  ${.::Core/Src/test.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::Core/Src/test.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h"    /* QP-nano framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "test.h"

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Test_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Test_ctor} ........................................................*/
void Test_ctor(Test* const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&Test_initial));
}
/*$enddef${AOs::Test_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Test} .............................................................*/

/*${AOs::Test::SM} .........................................................*/
QState Test_initial(Test * const me) {
    /*${AOs::Test::SM::initial} */
    return Q_TRAN(&Test_startup);
}

/*${AOs::Test::SM::button1} ................................................*/
QState Test_button1(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::button1} */
        case Q_ENTRY_SIG: {
            BSP_LED1_On();
            BSP_LED2_Off();
            QActive_armX(&me->super, 0U, 500U, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Test::SM::button1::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Test_shutdown);
            break;
        }
        /*${AOs::Test::SM::button1::BUTTON1_CLICK} */
        case BUTTON1_CLICK_SIG: {
            status_ = Q_TRAN(&Test_shutdown);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Test::SM::button2} ................................................*/
QState Test_button2(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::button2} */
        case Q_ENTRY_SIG: {
            BSP_LED1_Off();
            BSP_LED2_On();
            QActive_armX(&me->super, 0U, 500U, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Test::SM::button2::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Test_shutdown);
            break;
        }
        /*${AOs::Test::SM::button2::BUTTON2_CLICK} */
        case BUTTON2_CLICK_SIG: {
            status_ = Q_TRAN(&Test_shutdown);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Test::SM::startup} ................................................*/
QState Test_startup(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::startup} */
        case Q_ENTRY_SIG: {
            //BSP_CheckCheckNoButtonWakeup();
            BSP_CheckButton1Wakeup();
            BSP_CheckButton2Wakeup();


            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Test::SM::startup::BUTTON1_CLICK} */
        case BUTTON1_CLICK_SIG: {
            status_ = Q_TRAN(&Test_button1);
            break;
        }
        /*${AOs::Test::SM::startup::BUTTON2_CLICK} */
        case BUTTON2_CLICK_SIG: {
            status_ = Q_TRAN(&Test_button2);
            break;
        }
        /*${AOs::Test::SM::startup::NO_BUTTON_WAKEUP} */
        case NO_BUTTON_WAKEUP_SIG: {
            status_ = Q_TRAN(&Test_shutdown);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Test::SM::shutdown} ...............................................*/
QState Test_shutdown(Test * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Test::SM::shutdown} */
        case Q_ENTRY_SIG: {
            Shutdown();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
